### ISSUE TITLE
Filtering tags with atlas

### ISSUE THREAD

**Issue by gasabr** [mihairaulea/atlas#1]
Hello, for my application I need to import osm data in neo4j, but in the raw form my laptop was not able to handle all 1.6M+ nodes. Does your library allows to filter from all the data only buildings, routes and transport able to go on this routes?

**Comment by mihairaulea** [comment]
Hello, i would advise writing to the database as soon as you encounter a node, this way you do not need to keep everything in-memory. Yes, Atlas is able to filter through those entities, please see the docs.
